language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

# Display Gradle version instead of letting Travis execute './gradlew assemble' by default
install:
  - ./gradlew -version

script:
  - ./gradlew check --scan